# Generated by Django 4.1.5 on 2023-01-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
