# Generated by Django 4.0.2 on 2022-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=100)),
                ('order_price', models.FloatField()),
                ('order_quantity', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mobile_no', models.IntegerField()),
                ('deliver_to', models.CharField(max_length=100)),
            ],
        ),
    ]
